### ISSUE TITLE
Issue in "Wooden Walkway"

### ISSUE THREAD

**Issue by darkwarriorx05459** [GateteVerde/Gatete-Mario-Engine-9#18] opened 2024-05-12 13:02 UTC
When trying to jump on the red note block, the game crashes and shows this error message:

```
############################################################################################
ERROR in
action number 1
of  Step Event0
for object obj_fade_in:

room_goto argument 1 invalid reference to (room) - requested -1 max is 43
 at gml_Object_obj_fade_in_Step_0 (line 19) -     room_goto(target);
############################################################################################
gml_Object_obj_fade_in_Step_0 (line 19)
```

![Zrzut ekranu 2024-05-12 150146](https://github.com/GateteVerde/Gatete-Mario-Engine-9/assets/169006086/20efe26d-f459-4399-ad0f-4aa05eeca228)
![Zrzut ekranu 2024-05-12 150155](https://github.com/GateteVerde/Gatete-Mario-Engine-9/assets/169006086/536626cd-0cd0-44cd-912f-c27c52c58d9f)

**Comment by GateteVerde** [comment] 2024-05-13 12:03
Not a bug, no room is assigned to that block

**Closed by GateteVerde** 2024-05-13 12:03 UTC
